## Random Forest 
 - No Overfitting
 - Traning Time is less
 - High Accuracy
 - Estimates Missing data

In Random forest, it Constructing multiple decision tree, and final deision is made by majority of tree

<img src = "./img/multiple_trees.png" width=900>

### Decision - Tree

 - Determine course of Action
 - Each branch determine/represents possiable, decision, occurance and reaction
 - Its affect By :-
           1. Entropy - Measure of randomness or unpredictability
           2. Information Gain - Measure of decrease in entropy after spliting dataset 
           3. Leaf Node - last node in tree
           4. Decision node - nodes
           5. Root Node - very first node

 <img src = "./img/random_forest.png" width=900>
 
 ### How Does Random Forest Work ?
 
 <img src = "./img/work_random_forest.png" width=900>

In [1]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
np.random.seed(0)

In [3]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
# Adding new column for specis name
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [8]:
df['is_train'] = np.random.uniform(0,1,len(df)) <= .75
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [9]:
train, test = df[df['is_train'] == True], df[df['is_train'] == False]

print('No. of Traning Data : ', len(train))
print('No. of Test Data : ', len(test))

No. of Traning Data :  118
No. of Test Data :  32


In [12]:
features = df.columns[:4]
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [18]:
y = pd.factorize(train['species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
clf = RandomForestClassifier(n_jobs = 2, random_state = 0)
clf.fit(train[features], y)

/home/saurus/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [20]:
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
# View the predicted probabilities of the first 10 Observations
clf.predict_proba(test[features][10:20])

array([[1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.5, 0.5],
       [0. , 1. , 0. ],
       [0. , 0.9, 0.1],
       [0. , 0.2, 0.8],
       [0. , 0.3, 0.7],
       [0. , 1. , 0. ],
       [0. , 0.8, 0.2]])

In [31]:
pred = iris.target_names[clf.predict(test[features])]
pred[:5]
# this is done by forest

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [32]:
test['species'].head()
# this is actual values

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

In [34]:
# Creating Confusion Matrix
pd.crosstab(test['species'], pred, rownames = ['Actual Species'], colnames = ['Predicted Species'])

# crosstab take two sets of data and create chart out of it 

Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12

Number of Accurate Predictions = 30 (13 + 5 + 12)
Number of Inaccurate Prdictions = 2

therefore the <b>Model Accuracy is 93%</b>

<b>(30 / 32) x 100 = 93</b>

In [36]:
preds = iris.target_names[clf.predict([[5.0, 3.6, 1.4, 2.0], [5.0, 3.6, 1.4, 2.0]])]
preds

array(['versicolor', 'versicolor'], dtype='<U10')

### Other Resources 

1. [Random Forest Slide](https://goo.gl/K8T4tW)